# A simplified and updated GitHub Action to compile two LaTeX resumes and deploy them with a landing page.

name: Build and Deploy Resumes

on:
  # Run this workflow only when changes are pushed to the 'main' branch
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    # Grant permissions for the workflow to write to the repository (for deploying to the 'build' branch)
    permissions:
      contents: write
      
    steps:
      # Step 1: Check out the repository content (your .tex files, index.html, etc.)
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Compile both LaTeX documents into PDFs
      # This action will find both .tex files and compile them, creating cv_en.pdf and cv_ptbr.pdf
      - name: Compile LaTeX documents
        uses: xu-cheng/latex-action@v3
        with:
          # List all the main .tex files you want to compile
          root_file: |
            cv_en.tex
            cv_ptbr.tex
          # Using lualatex as the compiler
          compiler: lualatex

      # Step 3: Deploy the generated PDFs and the index.html to the 'build' branch
      # This branch is then used by GitHub Pages to serve your site.
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          # The token is provided automatically by GitHub
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # The branch to which the files will be deployed
          publish_branch: build
          # The directory to deploy. '.' means the current directory, which now contains
          # cv_en.pdf, cv_ptbr.pdf, and your checked-out index.html.
          publish_dir: .
          # force_orphan creates a clean history on the deployment branch each time
          force_orphan: true
